version: "2"
services:
  node:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - NODE_PORT=80
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 80:80